version: '3'
services: 
    postgres:
        image: postgres:${POSTGRES_VERSION:-9.6.15-alpine}
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - "5432:5432"
    redis:
        image: 'redis:latest'
    
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'

    api:
        depends_on: 
            - postgres
            - redis
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres 
            - PGHOST=postgres
            - PGPORT=5432
            - PGDATABASE=postgres
            - PGPASSWORD=postgres    
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        